{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vectorflow.serviceAccountName" . }}
  labels:
    {{- include "vectorflow.labels" . | nindent 4 }}
{{- end }} 